version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /usr/react-app/node_modules
      - ./:/usr/react-app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/react-app/node_modules
      - ./:/usr/react-app
    command: ["npm", "run", "test"]